# SkyAntiXray
# karpen-dev - https://github.com/karpen-dev/

# Время (в миллисекундах) для обнаружения подозрительной активности
thresholdTime: 120000

# Минимальное количество разрушений алмазной руды, необходимых для срабатывания
requiredBreaks: 4